language: java
script:
  - ./gradlew fatJar
deploy:
  provider: releases
  api_key:
    secure: ePZUjRJ253OAndjq3B5b/24NWBcvXCrFZ/nLfoiUL8AM9OMeagHuGGpbtdcPtCA2aeFAePKWfV3zsnA8ylIr2e7LDF9HZcLKbSinqAGl62K3Cn2u9SYCPJgDpDEGD0yuBtIB04L0CovgsEzA0tvriWarxqEagMmh+XMMlh5I99JHWrG5oq8CevuEKRlXzRsTNPgPIVOA+x0nm3gP9b9f7bc5Pdh+ZuwlFDEiYNFufk5ulF/6SLS7kCuXUzcpWkusqcMLCeYPdEcCCK1TFBgj4DDbIn8zWCXlaKXKl6imon4UjTV+qIVAVFIGSzicHKv6PFKqTECd7EJRxocSsM54VI5NLgGTnZLDKLMgHE8Sxum9eV53L7dBlqi50IS2e/S92fBaFi6R2GPbPXVcaPQQ0Pt96bGT4YsQxbO8S800v9NGmu6TJ9iMu0DHVjd2sNJ0CFw1nq/TAOsLjLdlAUzE4e8Rhp1tgFhhLL5j2LhfdoYLlseN6unpHDImhfDFBUS8KzV8+wG/rJ5XNJe22lrYhxzvkSvogSpvKrt15H3ruMDRCV3XOZqs9mlTu/JvlG14BJa3DoxZcOfeYZ99NksMgMoeJaLyeVkY+LDScXKIIZO36BJsJjbKiW7u0bWI2vTsSmUew66oFaC2tu1nWHXc2EfqmqlPWKgd4Gb7MmzQnbY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xl-ci-tool
