language: java
deploy:
  provider: releases
  api_key:
    secure: hGNrdmT68YMFdKb0pe8m2b/qkxmP+av78JHSJ3OxkiFYTvPC62K7h6op1VIu1isAwukpWDMvWGc0vut7kzkEufKfssjZTGCNs9Ib6n/bHGPlnGtIZK66J21/22TwleebEMGrwFO9JxX6ZhErW/hgGi2tsVqTuvvgnBPuzKtRhl43misfEkt7z4ofSC16s/T95HJwNpTH3WnGgeW1b4RCXGGe92KdQZk6ARVpHXNAVcZpqrkLwwNDV6iSRjdRBJuY2P+jud29I2OJk5ItzYzmYX601xlud1UHLSu/32GZqEbeyWXFJxKCeUtQLhMHk7s1OZCAU0rOtMyq/G8FfUGp7tiSW07/Y8OzUhgATgCKtczmQRyx1WogwKkaG4bZtCmhNTy+US2s0a1plXOG2qMaS9Zo6pcTC5cX2jekLrdt6I6+ZGHghzLz4u/1MDj2KUgRUw6nCCuuaEln+03P5f+4LzR9ti2WKi5guLolkMO2GwqdJI6N979fzwolxw88idK12S+vk8kvn05bcW2MiI1c0IJZK1ISCYz1CVqCuA8qodzP94yW4wGooHgLSXQrQP5sfl1JRCPc7ukMNasJTunQpLOP59jdOajz+qeTnjdochBTMcZLk5CNNvO/IJKRUG5QTkksez7V395kewUuQm9icd80sL5nScK4qDsOPfyKumk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xl-ci-tool
